casys/urls.py
from . import views
from django.urls import path, include

app_name = 'casys'
urlpatterns = [
    path('create-client/', views.AddClient, name="create-client"),
    path('create-product/', views.AddProduct, name="create-product"),
    path('create-order/', views.AddOrder, name="create-order"),
    path('create-shipment/', views.AddShipment, name="create-shipment"),
    path('create-received/', views.AddReceived, name="create-received"),

    path('update-client/<str:pk>/', views.UpdateClient, name="update-client"),

    path('delete-client/<str:pk>/', views.DeleteClient, name="delete-client"),
    path('delete-order/<str:pk>/', views.DeleteOrder, name="delete-order"),

    path('', views.HomePage, name="home"),
    path('order/', views.OrderView, name="order"),
    path('products/', views.ProductView, name="products"),
    path('feedback/', views.FeedbackView, name="feedback"),
    path('feedback/<int:pk>/', views.FeedbackDetail.as_view(), name='feedback-detail'),
    path('client/', views.ClientView, name="client"),

    path('login/', views.loginPage, name='login'),
]

joselleproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('casys.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casys/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

class Client(models.Model):
	firstname= models.CharField(max_length=200)
	surname = models.CharField(max_length=200)
	address = models.TextField()
	contact_number = PhoneNumberField(null=False,blank=False,unique=True)
    
	def __str__(self):
         return f'{self.firstname} {self.surname}'

class Product(models.Model):
	product_name = models.CharField(max_length=24, unique=True)
	art_medium = models.CharField(max_length=300)
	size = models.CharField(max_length=200)
	price = models.CharField(max_length=24)
	quantity=models.IntegerField()

	def __str__(self):
		 return self.product_name

class Order(models.Model):
    COURIER = (('jt', 'J&T Express'), ('lm', 'lala move'), ('lbc', 'LBC Hari ng Padala'))
    user_information = models.ForeignKey(Client, on_delete = models.CASCADE)
    product_name = models.ForeignKey(Product, on_delete = models.CASCADE)
    reference_picture = models.ImageField(null=True, blank=True, upload_to="images/")
    courier = models.CharField(max_length=300, choices=COURIER)
    gcash_number = PhoneNumberField(null=False,blank=False)
    gcash_name = models.CharField(max_length=300)
    proof_of_payment = models.CharField(max_length=300)

    def __str__(self):
        return '%s-%s' % (self.pk, self.user_information)

class Shipment(models.Model):
	order_name = models.ForeignKey(Order, on_delete = models.CASCADE)
	date_to_ship = models.DateField()
	time_to_ship = models.TimeField(auto_now = False, auto_now_add = False)

	def __str__(self):
		return '%s-%s' % (self.order_name, self.pk)

class Product_Receive(models.Model):
	recipient_name =  models.ForeignKey(Client, on_delete = models.CASCADE)
	order_name = models.ForeignKey(Order, on_delete = models.CASCADE)
	proof_received = models.ImageField(null=True, blank=True, upload_to="images/")
	feedback = models.TextField()

	def __str__(self):
		return f'{self.recipient_name}'

casys/forms.py
from django.forms import ModelForm
from .models import *
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.DateInput):
    input_type = 'time'

class CreateClient(ModelForm):
    class Meta:
        model = Client
        fields = ['firstname', 'surname', 'contact_number', 'address']

# admin page
class CreateProduct(ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'art_medium', 'size', 'price', 'quantity']

class CreateOrder(ModelForm):
    class Meta:
        model = Order
        fields = ['user_information', 'product_name', 'reference_picture', 'courier', 'gcash_number', 'gcash_name', 'proof_of_payment']
        
class CreateShipment(ModelForm):
    class Meta:
        widgets = {'date_to_ship':DateInput(), 'time_to_ship':TimeInput()}
        model = Shipment
        fields = ['order_name', 'date_to_ship', 'time_to_ship']

class CreateReceived(ModelForm):
    class Meta:
        model = Product_Receive
        fields = ['recipient_name', 'order_name', 'proof_received', 'feedback']

casys/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.utils import timezone
from .models import Client, Order, Shipment, Product_Receive, Product

from django.views import generic
from django.http import Http404, HttpResponse
from casys.forms import CreateClient, CreateProduct, CreateOrder, CreateShipment, CreateReceived

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def HomePage(request):
	return render(request, 'home.html')

def OrderView(request):
    order = Order.objects.all()
    queries = {'order': order}
    return render(request, "orders.html", queries)

def ClientView(request):
    client = Client.objects.all()
    queries = {'client': client}
    return render(request, "client.html", queries)

def ProductView(request):
    product = Product.objects.all()
    queries = {'product': product}
    return render(request, "products.html", queries)

def ShipmentView(request):
    shipment = Shipment.objects.all()
    queries = {'shipment': shipment}
    return render(request, "shipments.html", queries)

class FeedbackDetail(generic.DetailView):
    model = Product_Receive
    template_name = 'feedback-detail.html'

def FeedbackView(request):
    feedback = Product_Receive.objects.all()
    queries = {'feedback': feedback}
    return render(request, "feedback.html", queries)

def AddClient(request):
    form = CreateClient()
    if request.method == 'POST':
        client = CreateClient(request.POST)
        if client.is_valid():
            client.save()
            return redirect('casys:client')
    value = {'form':form}
    return render(request, 'create.html',value)

def AddOrder(request):
    form = CreateOrder()
    if request.method == 'POST':
        order = CreateOrder(request.POST)
        if order.is_valid():
            order.save()
            return redirect('casys:order')
    value = {'form':form}
    return render(request, 'create.html',value)

def AddShipment(request):
    form = CreateShipment()
    if request.method == 'POST':
        shipment = CreateShipment(request.POST)
        if shipment.is_valid():
            shipment.save()
            return redirect('casys:order')
    value = {'form':form}
    return render(request, 'create.html',value)

def AddReceived(request):
    form = CreateReceived()
    if request.method == 'POST':
        received = CreateReceived(request.POST, request.FILES)
        if received.is_valid():
            received.save()
            return redirect('casys:feedback')
    value = {'form':form}
    return render(request, 'create.html',value)

@login_required(login_url='casys:login')
def AddProduct(request):
    form = CreateProduct()
    if request.method == 'POST':
        product = CreateProduct(request.POST)
        if product.is_valid():
            product.save()
            return redirect('casys:products')
    value = {'form':form}
    return render(request, 'create.html',value)

def UpdateClient(request,pk):
    updateditem = Client.objects.get(id=pk)
    form = CreateClient(instance=updateditem)
    if request.method == "POST":
        client = CreateClient(request.POST,instance=updateditem)
        if client.is_valid:
            client.save()
            return redirect('casys:client')

    value = {'form':form}
    return render(request, 'create.html',value)

def DeleteClient(request,pk):
    deleteclient = Client.objects.get(id=pk)
    if request.method == "POST":
        deleteclient.delete()
        return redirect('casys:client')
    value = {'item':deleteclient}
    return render(request, 'create.html',value)

def DeleteOrder(request,pk):
    deleteorder = Order.objects.get(id=pk)
    if request.method == "POST":
        deleteorder.delete()
        return redirect('casys:order')
    value = {'item':deleteorder}
    return render(request, 'create.html',value)

def loginPage(request):
    if request.method == 'POST':
        un = request.POST.get('username')
        pw = request.POST.get('Password')

        user = authenticate(request, username = un, password =pw)

        if user is not None:
            login(request, user)
            return redirect('casys:products')
    return render(request, "login.html")

casys/templates/addclient.html
{% extends 'base.html' %}
{% block title %}Form{% endblock %}

{% block content %}

</form>
	<form id="review" method="POST">
    <fieldset>
	<h1><center>Register Now!</center></h1>
	<label>First Name: 
		<input type="text" id="first" name="first" placeholder="Enter your first name here.">  
	</label>
    <br>
    <label>Surname: 
        <input type="text" id="last" name="last" placeholder="Enter your last name here.">
    <br>
    <label>address: 
        <input type="text" id="address" name="address" placeholder="Enter your number here.">
    </label>
    <br>
    <label>contact number: 
        <input type="text" id="contact" name="contact" placeholder="Enter your number here.">
    </label>
    <br>
    <br>
    <label>
        <input type="submit" id="btn" name="btn" value="Submit">
    </label>
    </fieldset>
  {% csrf_token %}
	</form>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

casys/templates/addorder.html
{% extends 'base.html' %}
{% block title %}Form{% endblock %}

{% block content %}

</form>
  {% csrf_token %}
	<form id="review" method="POST">
    <fieldset>
	<h1><center>Register Now!</center></h1>
	<label>User Information: 
		<input type="text" id="first" name="user_information" placeholder="Enter your first name here.">  
	</label>
    <br>
    <label>Product name: 
        <input type="text" id="last" name="product_name" placeholder="Enter your last name here.">
    <br>
    <label>Reference picture: 
        <input type="text" id="address" name="referece_picture" placeholder="Enter your number here.">
    </label>
    <br>
    <label>Courier: 
        <input type="text" id="contact" name="courier" placeholder="Enter your number here.">
    </label>
    <label>Gcash number: 
        <input type="text" id="contact" name="gcash_number" placeholder="Enter your number here.">
    </label>
    <label>Gcash name: 
        <input type="text" id="contact" name="gcash_name" placeholder="Enter your number here.">
    </label>
    <label>Proof of payment: 
        <input type="text" id="contact" name="proof_of_payment" placeholder="Enter your number here.">
    </label>
    <br>
    <br>
    <label>
        <input type="submit" id="btn" name="btn" value="Submit">
    </label>
    </fieldset>
    {% csrf_token %}
	</form>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

casys/templates/base.html
<!-- base.html -->
<!doctype html>
{% load static %}
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#a96e58;
			overflow-x: :hidden;
			padding-top:20px;
		}    

      .sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #ffffee;
			display:block;
		}  
  
      .sidenav a:hover{
			color:#246E86;
		}     

      .main{
			margin-left:160px;
			padding: 0px 10px;
      }

      body{
      background-color:#03a9f4;
      }
    </style>

	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
 
	<title>{% block title %}CICLEDO Site{% endblock %}</title>
</head>
 
<body style="background-color:#ffe7d9;">
	<div class="sidenav">
    <a href="{% url 'casys:home' %}">Home</a>
    <a href="{% url 'casys:client' %}">Profiles</a>
    <a href="{% url 'casys:products' %}">Products</a>
    <a href="{% url 'casys:order' %}">Orders</a>
    <a href="{% url 'casys:create-shipment' %}">Shipments</a>
    <a href="{% url 'casys:feedback' %}">Feedbacks</a>
	</div>
 
	<div id="content" name="content" class="main">
		<div class="row justify-content-center">
			<div class="col-8">
				<hr class="mt-0 mb-4">
				{% block content %}
				{% endblock %}
			</div>
	</div>
 
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>

casys/templates/client.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Client Profile {% endblock %}

{% block content %}

<h1>Client Profile</h1>

 <table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Address</th>
      <th scope="col">Contact Number</th>
    </tr>
  </thead>
  <tbody>

    {% for x in client %}
    <tr>
      <td>{{x.firstname }}</td>
      <td>{{x.surname }}</td>
      <td>{{x.address }}</td>
      <td>{{x.contact_number }}</td>
      <td> 
        <a href="{% url 'casys:update-client' x.id %}" class="btn btn-primary">Update Profile</a>
      </td>
      <td> 
        <a href="{% url 'casys:delete-client' x.id %}" class="btn btn-danger">Delete Profile</a>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table> 

<a href="{% url 'casys:create-client' %}" class="btn btn-primary">Sign up</a>
{% endblock %}

casys/templates/create.html
{% extends 'base.html' %}
{% block title %}Form{% endblock %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
  <div class="card card-body">
    {% for x in form %}
    {{x.label}}
    {{x}} <br>
    {% endfor %}
    <input type="submit" name="submit">
  </div>
  {% csrf_token %}
</form>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

casys/templates/feedback-detail.html
{% extends 'base.html' %}
{% block title %}Form{% endblock %}

{% block content %}

<h3>Recipient</h3>
{{ product_receive.recipient_name }}
<br>  
<h3>Order Identification</h3> 
{{ product_receive.order_name }}
<h3>Feedback</h3>
{{ product_receive.feedback }}
<h3>Proof</h3>

  {% if product_receive.proof_received %}
  <img src="{{ product_receive.proof_received.url }}" class="img-fluid">
  {% endif %}

{% endblock %}

casys/templates/feedback.html
{% extends 'base.html' %}
{% block title %}Shipped products and Feedbacks{% endblock %}

{% block content %}

<h1>Shipped products and Feedbacks</h1>

{% for x in feedback %}
<a href="/feedback/{{x.id}}">{{ x.order_name }}</a><br>
{% endfor %}

<hr>
<a href="{% url 'casys:create-received' %}" class="btn btn-primary">Submit feedback</a>
{% endblock %}

casys/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} CentArt {% endblock %}

{% block content %}

<img src="/media/images/jzl.png" class="img-fluid">

{% endblock %}

casys/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Clients {% endblock %}

{% block content %}

<h1>Clients</h1>

 <table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Contact Info</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>

    {% for x in client %}
    <tr>
      <td><a href="{{x.id}}">{{ x.firstname }} {{x.surname}}</a></td>
      <td>{{x.contact_number }}</td>
      <td>{{x.address }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table> 

{% endblock %}

casys/templates/login.html
{% load static %}
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
 
	<title>{% block title %}Login{% endblock %}</title>
</head>

<body>

<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <form method="POST">
          {%csrf_token%}

  <h1>Login Required to add Products</h1>
          <!-- username input -->
          <div class="form-outline mb-4">
            <input type="text" class="form-control form-control-lg" placeholder="Username" name="username"/>
            <label class="form-label" for="username">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-4">
            <input type="password"  class="form-control form-control-lg" placeholder="Password" name="Password"/>
            <label class="form-label" for="password">Password</label>
          </div>

          <!-- Login button -->
          <button type="submit" class="btn btn-primary">Sign in</button>

        </form>
      </div>
    </div>
  </div>
</section>

</body>
</html>

casys/templates/orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Orders {% endblock %}

{% block content %}

<h1>Orders</h1>

 <table class="table">
  <thead>
    <tr>
      <th scope="col">Client Information</th>
      <th scope="col">Product Name</th>
      <th scope="col">Reference Picture</th>
      <th scope="col">Courier</th>
      <th scope="col">Gcash Number</th>
      <th scope="col">Gcash Name</th>
      <th scope="col">Proof of Payment</th>
    </tr>
  </thead>
  <tbody>

    {% for x in order %}
    <tr>
      <td>{{x.user_information }}</td>
      <td>{{x.product_name }}</td>
      <td>{{x.reference_picture }}</td>
      <td>{{x.courier }}</td>
      <td>{{x.gcash_number }}</td>
      <td>{{x.gcash_name }}</td>
      <td>{{x.proof_of_payment }}</td>
      <td><a href="{% url 'casys:delete-order' x.id %}">Cancel Order</a><td> 
    </tr>
    {% endfor %}

  </tbody>
</table> 

<a href="{% url 'casys:create-order' %}" class="btn btn-primary">Order Items</a>
{% endblock %}

casys/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Products{% endblock %}

{% block content %}

<h1>Products</h1>

 <table class="table">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Medium</th>
      <th scope="col">Size</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>

    {% for x in product %}
    <tr>
      <td>{{x.product_name }}</td>
      <td>{{x.art_medium }}</td>
      <td>{{x.size }}</td>
      <td>{{x.price }}</td>
      <td>{{x.quantity }}</td>
      <td><a href="{% url 'casys:create-order' %}" class="btn-primary">Order Now</a></td>
    </tr>
    {% endfor %}

  </tbody>
</table> 

<a href="{% url 'casys:create-product' %}" class="btn btn-primary">Add Products</a>

{% endblock %}